### ISSUE TITLE
Calculations take a long time (>1 hour) if there is no chain ID assigned

### ISSUE THREAD

**Issue by matvey83** [jensengroup/propka#19] opened 2018-03-26 15:28 UTC
Take any PDB file, set chain name to " " for all atoms, and attempt to run it through propka.  Notice that the job takes a long time to run. PPREP-1218

**Comment by speleo3** [comment] 2020-12-03 09:55
I cannot reproduce this. Setting the chain identifier to " " has no affect on runtime duration in my tests.

**Comment by speleo3** [comment] 2020-12-03 11:13
Closing this. I found the downstream issue in the Schrodinger script which calls propka. Propka reports empty chain as "_" and the script didn't handle that.

**Closed by speleo3** 2020-12-03 11:13 UTC
Labels: I/O, need more information, performance
