### ISSUE TITLE
Exception thrown when alternate location indicator is not 1, A or whitespace

### ISSUE THREAD

**Issue by stcmz** [jensengroup/propka#20] opened 2019-04-03 19:32 UTC
Traceback (most recent call last):
  File "/home/ryan/.local/bin/propka31", line 11, in <module>
    load_entry_point('PROPKA==3.1.0', 'console_scripts', 'propka31')()
  File "/home/ryan/.local/lib/python3.6/site-packages/PROPKA-3.1.0-py3.6.egg/propka/run.py", line 13, in main
  File "/home/ryan/.local/lib/python3.6/site-packages/PROPKA-3.1.0-py3.6.egg/propka/molecular_container.py", line 46, in __init__
  File "/home/ryan/.local/lib/python3.6/site-packages/PROPKA-3.1.0-py3.6.egg/propka/molecular_container.py", line 88, in top_up_conformations
KeyError: '1A'

**Comment by sobolevnrm** [comment] 2020-05-31 17:51
Do you have a specific PDB we can use to troubleshoot this issue?

**Comment by speleo3** [comment] 2020-12-07 08:53
I do get a warning, but no error.

[example-pdb.txt](https://github.com/jensengroup/propka/files/5651533/example-pdb.txt)

**Comment by speleo3** [comment] 2023-12-19 10:56
Duplicate of https://github.com/jensengroup/propka/issues/147

**Closed by speleo3** 2023-12-19 10:56 UTC
Labels: need more information, I/O
